server:
  port: 8080
  undertow:
    threads:
      worker: 16
      io: 4
    buffer-size: 16364
    direct-buffers: true
  tomcat:
    threads:
      max: 2000

dubbo:
  application:
    name: my-experiment-server
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: N/A
  provider:
    threads: 32


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    #    sentinel:    #哨兵模式
    #      master: mymaster #主服务器所在集群名称
    #      nodes: 192.168.65.60:26379,192.168.65.60:26380,192.168.65.60:26381
#    cluster:
#      nodes: 192.168.50.61:8001,192.168.50.62:8002,192.168.50.63:8003,192.168.50.61:8004,192.168.50.62:8005,192.168.50.63:8006
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000

  data:
    mongodb:
      uri: mongodb://192.168.229.130:27017/appdb

  datasource:
    url: jdbc:mysql://localhost:3306/experiment?useSSL=false&autoReconnect=true&characterEncoding=utf8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      initial-size: 10 # 以下是连接池配置
      max-active: 100
      min-idle: 10
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 180000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-evictable-idle-time-millis: 300000

mybatis-plus:
  check-config-location: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
logging:
  level:
    root: info

#nacos源码启动-Dmaven.test.skip=true -Drat.skip=true
gamewhitelist:
  channelSet:
    - media_source
    - bigoads_int
    - kwaiforbusiness_int
    - huaweiadsglobal_int
    - bytedanceglobal_int
    - shalltry_int
    - snapchat_int
    - 社媒下载链接
    - mail.ru_int
    - KOL
    - huawei
    - Social_tiktok
    - Facebook Ads
    - shareit_int
    - Social_youtube